ListaTarefas/Models/ErrorViewModel.cs
namespace ListaTarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ListaTarefas/Models/Tarefa.cs
using System.ComponentModel.DataAnnotations;

namespace ListaTarefas.Models;

public class Tarefa
{
    public int TarefaId { get; set; }
    public string Nome { get; set; }
    public Boolean Concluida { get; set; } = false;
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
    public DateTime DtInicio { get; set; } = DateTime.Now;
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
    public DateTime? DtConclusao { get; set; }

}    

ListaTarefas/Controllers/HomeController.cs
using ListaTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ListaTarefas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ListaTarefas/Controllers/TarefasController.cs
using ListaTarefas.Models;
using Microsoft.AspNetCore.Mvc;

namespace ListaTarefas.Controllers;

public class TarefasController : Controller
{
    private static List<Tarefa> _tarefas = new List<Tarefa>
    {
        new Tarefa {TarefaId = 1, Nome = "Estudar projetos MVC", DtInicio = DateTime.Parse("08/05/2024"),Concluida = true, DtConclusao = DateTime.Parse("09/05/2024")},
        new Tarefa {TarefaId = 2, Nome = "Estudar Azure", DtInicio = DateTime.Parse("09/05/2024"),  Concluida = true, DtConclusao = DateTime.Parse("10/05/2024")},
        new Tarefa {TarefaId = 3, Nome = "Responder questionário"},
        new Tarefa {TarefaId = 4, Nome = "Entregar projeto de lista de tarefas"},
        new Tarefa {TarefaId = 5, Nome = "1:1 com professor para feedback"}
    };

    public IActionResult Index()
    {
        return View(_tarefas);
    }

    public IActionResult Delete(int id)
    {
        var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
        if (tarefa == null)
            return NotFound();
        _tarefas.Remove(tarefa);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Tarefa tarefa)
    {
        if (ModelState.IsValid)
        {
            tarefa.TarefaId = _tarefas.Count() > 0 ? _tarefas.Max(t => t.TarefaId + 1) : 1;
            _tarefas.Add(tarefa);
        }
        return RedirectToAction("Index");
    }

    public IActionResult Edit(int id)
    {
        var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
        if (tarefa == null)
        {
            return NotFound();
        }

        return View(tarefa);
    }

    [HttpPost]
    public IActionResult Edit(Tarefa tarefa)
    {
        if (ModelState.IsValid)
        {
            var existingTarefa = _tarefas.FirstOrDefault(t => t.TarefaId == tarefa.TarefaId);
            if (existingTarefa != null)
            {
                existingTarefa.Nome = tarefa.Nome;
            }
            return RedirectToAction("Index");
        }
        return View(tarefa);
    }

    public IActionResult Concluidas()
    {
        var _tarefasConcluidas = _tarefas.Where(t => t.Concluida == true).ToList();

        return View(_tarefasConcluidas);
    }

    public IActionResult PorFazer()
    {
        var _tarefasPorFazer = _tarefas.Where(t => t.Concluida == false).ToList();

        return View(_tarefasPorFazer);
    }

}

ListaTarefas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ListaTarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ListaTarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ListaTarefas.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/styleComplemento.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Tarefas" asp-action="Index">
                    <i class="bi bi-check-square-fill"></i> Lista de Tarefas
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Concluidas">Concluídas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="PorFazer">Por Fazer</a>
                        </li>
                    </ul>
                    <a asp-controller="Tarefas" asp-action="Create" class="btn btn-success"><i class="bi bi-plus"></i> Criar nova tarefa</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; <i class="bi bi-check-square-fill"></i> Lista de Tarefas (2024) - Desenvolvido por Maria Eduarda Lemos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ListaTarefas/Views/Tarefas/Concluidas.cshtml
@{
    ViewData["Title"] = "Tarefas concluídas";
}

@model List<Tarefa>

<h2 class="text-center titulo-app"><i class="bi bi-check-square-fill"></i> Lista de Tarefas</h2>

<br />

<h4>Tarefas concluídas</h4>
<table class="table text-center">
    <tr>
        <th>Tarefa</th>
        <th>Concluída</th>
        <th>Criada em</th>
        <th>Concluída em</th>
        <th></th>
    </tr>
    <tbody>
        @foreach (var tarefa in Model)
        {
            <tr>
                <td>@tarefa.Nome</td>
                <td>
                    @if (@tarefa.Concluida == true)
                    {
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
                    }
                    else
                    {
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                    }
                </td>
                <td>@Html.DisplayFor(modelItem => @tarefa.DtInicio)</td>
                <td>@Html.DisplayFor(modelItem => @tarefa.DtConclusao)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@tarefa.TarefaId" class="btn btn-primary"><i class="bi bi-pencil-square"></i> Editar</a>
                    <a asp-action="Delete" asp-route-id="@tarefa.TarefaId" class="btn btn-danger"><i class="bi bi-trash3-fill"></i> Apagar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ListaTarefas/Views/Tarefas/Create.cshtml
@{
    ViewData["Title"] = "Criar nova tarefa";
}

@model Tarefa

<h2 class="text-center titulo-app"><i class="bi bi-check-square-fill"></i> Lista de Tarefas</h2>
<br />
<form asp-action="Create" method="post">
    <div class="d-flex flex-row justify-content-between nova-tarefa-container">
        <input class="align-self-center input-nova-tarefa" type="text" placeholder="Crie uma nova tarefa..." aria-label="default input example" asp-for="Nome">
        <button type="submit" class="btn-add-tarefa"><i class="bi bi-plus"></i></button>
    </div>
</form>

ListaTarefas/Views/Tarefas/Edit.cshtml
@{
    ViewData["Title"] = "Editar tarefa";
}

@model Tarefa

<h2 class="text-center titulo-app"><i class="bi bi-check-square-fill"></i> Lista de Tarefas</h2>
<br />
<h5 class="text-center color-green">Atualize o nome da tarefa abaixo</h5>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="TarefaId" />
    <div class="d-flex flex-row justify-content-between nova-tarefa-container">
        <input class="align-self-center input-nova-tarefa" type="text" placeholder="" aria-label="default input example" asp-for="Nome">
        <div class="d-flex flex-row">
            <button type="submit" class="btn-add-tarefa"><i class="bi bi-check-lg"></i></button>
            <button type="button" class="btn-voltar"><a asp-action="Index"><i class="bi bi-x-lg"></i></a></button>
        </div>

    </div>
</form>

ListaTarefas/Views/Tarefas/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

@model List<Tarefa>

<h2 class="text-center titulo-app"><i class="bi bi-check-square-fill"></i> Lista de Tarefas</h2>

<br />

<table class="table text-center">   
    <tr>
        <th>Tarefa</th>
        <th>Concluída</th>
        <th>Criada em</th>
        <th>Concluída em</th>
        <th></th>
    </tr>
    <tbody>
        @foreach(var tarefa in Model){
            <tr>
                <td>@tarefa.Nome</td>
                <td>
                    @if(@tarefa.Concluida == true) {
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
                    } else {
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                    }
                </td>
                <td>@tarefa.DtInicio</td>
                <td>@tarefa.DtConclusao</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@tarefa.TarefaId" class="btn btn-primary"><i class="bi bi-pencil-square"></i> Editar</a>
                    <a asp-action="Delete" asp-route-id="@tarefa.TarefaId" class="btn btn-danger"><i class="bi bi-trash3-fill"></i> Apagar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ListaTarefas/Views/Tarefas/PorFazer.cshtml
@{
    ViewData["Title"] = "Tarefas por fazer";
}

@model List<Tarefa>

<h2 class="text-center titulo-app"><i class="bi bi-check-square-fill"></i> Lista de Tarefas</h2>

<br />

<h4>Tarefas por fazer</h4>
<table class="table text-center">
    <tr>
        <th>Tarefa</th>
        <th>Concluída</th>
        <th>Criada em</th>
        <th>Concluída em</th>
        <th></th>
    </tr>
    <tbody>
        @foreach (var tarefa in Model)
        {
            <tr>
                <td>@tarefa.Nome</td>
                <td>
                    @if (@tarefa.Concluida == true)
                    {
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
                    }
                    else
                    {
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                    }
                </td>
                <td>@Html.DisplayFor(modelItem => @tarefa.DtInicio)</td>
                <td>@Html.DisplayFor(modelItem => @tarefa.DtConclusao)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@tarefa.TarefaId" class="btn btn-primary"><i class="bi bi-pencil-square"></i> Editar</a>
                    <a asp-action="Delete" asp-route-id="@tarefa.TarefaId" class="btn btn-danger"><i class="bi bi-trash3-fill"></i> Apagar</a>
                </td>
            </tr>
        }
    </tbody>
</table>